---
- name: Install NTP package
  apt:
    name: ntp
    state: present
  become: true

- name: Configure NTP
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
    owner: root
    group: root
    mode: 0644
  become: true
  notify:
    - restart ntp

- name: Start NTP service
  service:
    name: ntp
    state: started
    enabled: true
  become: true
