---
- name: Update Root Password
  hosts: all
  become: yes
  vars_files:
    - group_vars/all.yml
  roles:
    - { role: cli_validation, tags: ['always'] }
    - { role: root_password, tags: ['always']}
