---
- name: Create or update systemd service files
  template:
    src: service.j2
    dest: "/etc/systemd/system/{{ item.name }}.service"
    mode: 0644
  loop: "{{ systemd_units }}"
  when: item.raw is defined

- name: Manage systemd services
  systemd:
    name: "{{ item.name }}"
    state: "{{ 'stopped' if item.state == 'stopped' and item.enabled == false else item.state | default('started') }}"
    enabled: "{{ true if item.enabled is not defined else item.enabled }}"
  loop: "{{ systemd_units }}"
