---

- name: Disable IPv6
  ansible.posix.sysctl:
    name: net.ipv6.conf.all.disable_ipv6
    state: "{{ ensure_state }}"
    value: 1
    sysctl_set: true
    reload: false
  become: true

- name: Disable IPv6 (default)
  ansible.posix.sysctl:
    name: net.ipv6.conf.default.disable_ipv6
    state: "{{ ensure_state }}"
    value: 1
    sysctl_set: true
    reload: true
  become: true
