---
- name: Update GRUB configuration
  copy:
    content: "GRUB_CMDLINE_LINUX_DEFAULT=\"{{ grub_config.cmdline_linux_default | join(' ') }}\""
    dest: /etc/default/grub.d/99-custom-settings.cfg
  become: true
  notify: Update GRUB

- name: Run update-grub command
  command: update-grub
