---

- name: Install common packages
  become: true
  ansible.builtin.apt:
    name: "{{ common_packages }}"
    state: "present"
    update_cache: true
  when: common_packages is defined

- name: Install group packages
  become: true
  ansible.builtin.apt:
    name: "{{ group_packages }}"
    state: "present"
  when: group_packages is defined

- name: Install host specific packages
  become: true
  ansible.builtin.apt:
    name: "{{ host_packages }}"
    state: "present"
  when: host_packages is defined
