---

- name: Install systemd-timesyncd
  become: true
  ansible.builtin.apt:
    name: "systemd-timesyncd"
    state: "present"

- name: Configure systemd-timesyncd
  become: true
  ansible.builtin.template:
    src: systemd-timesyncd.conf.j2
    dest: /etc/systemd/timesyncd.conf
    mode: 0644
    owner: root
    group: root
  notify: Restart systemd-timesyncd

- name: Enable systemd-timesyncd
  become: true
  ansible.builtin.service:
    name: systemd-timesyncd.service
    enabled: true
    state: started
