---
- name: Copy APT configuration file
  copy:
    content: "{{ apt_config_content }}"
    dest: /etc/apt/apt.conf.d/99custom
    mode: '0644'

- name: Add APT repositories
  apt_repository:
    repo: "{{ item.repo }}"
    state: present
  loop: "{{ apt_repositories }}"

- name: Install packages
  apt:
    name: "{{ item }}"
    state: present
  loop: "{{ apt_packages }}"
