---

- name: Disable cgroups v2
  ansible.builtin.include_tasks: "disable_cgroupsv2.yml"
  when: cgroupsv2_disabled is defined and cgroupsv2_disabled is true
  tags: ['always']

- name: Update GRUB configuration for hugepages
  ansible.builtin.copy:
    content: "GRUB_CMDLINE_LINUX_DEFAULT=\"{{ grub_config.cmdline_linux_default | join(' ') }}\""
    dest: /etc/default/grub.d/99-custom-settings.cfg
  become: true
  notify: update-grub

- name: "Flush handlers"
  ansible.builtin.meta: flush_handlers
  tags: ['always']

- name: Reboot
  become: true
  tags: ['never', 'reboot']
  ansible.builtin.reboot:
