---

- name: Generate /etc/systemds/resolved.conf file
  become: true
  vars:
    host_list: "{{ groups['hosts'] }}"
  ansible.builtin.template:
    src: templates/systemd-resolved.conf.j2
    dest: /etc/systemd/resolved.conf
    owner: root
    group: root
    mode: 0644
    backup: false
  notify: systemd-resolved.restart

- name: "Flush handlers"
  ansible.builtin.meta: flush_handlers
